name: Update URL and Redirects File

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch API Data and Save to url.txt
        run: |
          curl -sL "https://tvbox.catvod.com/xs/api.json" -o url.txt
          echo "✅ API 数据已保存到 url.txt"

      - name: Extract Site Values and Save to redirects.json
        run: |
          # 站点映射表（拼音首字母）
          declare -A sites=(
            ["立播"]="lb"
            ["闪电"]="sd"
            ["欧哥"]="og"
            ["小米"]="xm"
            ["多多"]="dd"
            ["蜡笔"]="lb"
            ["至臻"]="zz"
            ["木偶"]="mo"
            ["六趣"]="lq"
            ["虎斑"]="hb"
            ["下饭"]="xf"
          )

          # 提取 JSON 数据
          jq -r '.sites[] | select(.name | IN("立播","闪电","欧哥","小米","多多","蜡笔","至臻","木偶","六趣","虎斑","下饭")) | {(.name): .ext.site}' url.txt > temp.json

          # 生成 redirects.json
          echo "{" > redirects.json
          first=true
          for name in "${!sites[@]}"; do
            site_url=$(jq -r --arg name "$name" '.[$name]' temp.json)
            if [[ "$site_url" != "null" && "$site_url" != "" ]]; then
              [[ "$first" == "false" ]] && echo "," >> redirects.json
              first=false
              key=${sites[$name]}
              echo "  \"$key\": \"$site_url\", // $name" >> redirects.json
            fi
          done
          echo "}" >> redirects.json

          rm -f temp.json  # 删除临时文件
          echo "✅ redirects.json 生成完成"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add url.txt redirects.json
          git commit -m "Update url.txt & redirects.json from API" || echo "No changes to commit"
          git push origin HEAD:main

